server:
    port: 2222
    
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    statusPageUrlPath: ${management.contextPath}/info
    healthCheckUrlPath: ${management.contextPath}/health
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    serviceUrl:
      defaultZone: http://localhost:2222/eureka/   #necesary to eureka dont try to config peer zone in 8761 por by default
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0   
    
    

#spring.boot.admin.url: http://localhost:3333               