spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
        git:
          uri: https://github.com/rafabc/microservice-graphql
          default-label: master
          search-paths: microservice_config_server/src/main/resources/config
  profiles:
     active: native


eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:2222/eureka/}
    healthcheck:
      enabled: true
    lease:
      duration: 5  